{{- if and .Values.ingress.enabled .Values.ingress.middleware.enabled -}}
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  labels: {{ include "hedera-mirror-web3.labels" . | nindent 4 }}
  name: {{ include "hedera-mirror-web3.fullname" . }}
  namespace: {{ include "hedera-mirror-web3.namespace" . }}
spec:
  chain:
    middlewares:
    - name: {{ include "hedera-mirror-web3.fullname" . }}-ip-whitelist
    - name: {{ include "hedera-mirror-web3.fullname" . }}-connection-limit
    - name: {{ include "hedera-mirror-web3.fullname" . }}-rate-limit
    - name: {{ include "hedera-mirror-web3.fullname" . }}-circuit-breaker

---
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  labels: {{ include "hedera-mirror-web3.labels" . | nindent 4 }}
  name: {{ include "hedera-mirror-web3.fullname" . }}-ip-whitelist
  namespace: {{ include "hedera-mirror-web3.namespace" . }}
spec:
  ipWhiteList:
    sourceRange: {{ toYaml .Values.ingress.middleware.ipWhitelist | nindent 6 }}

---
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  labels: {{ include "hedera-mirror-web3.labels" . | nindent 4 }}
  name: {{ include "hedera-mirror-web3.fullname" . }}-connection-limit
  namespace: {{ include "hedera-mirror-web3.namespace" . }}
spec:
  inFlightReq:
    amount: {{ .Values.ingress.middleware.connectionsPerIP }}
    sourceCriterion:
      ipStrategy:
        depth: 1

---
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  labels: {{- include "hedera-mirror-web3.labels" . | nindent 4 }}
  name: {{ include "hedera-mirror-web3.fullname" . }}-circuit-breaker
  namespace: {{ include "hedera-mirror-web3.namespace" . }}
spec:
  circuitBreaker:
    expression: {{ .Values.ingress.middleware.circuitBreaker }}

---
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  labels: {{- include "hedera-mirror-web3.labels" . | nindent 4 }}
  name: {{ include "hedera-mirror-web3.fullname" . }}-rate-limit
  namespace: {{ include "hedera-mirror-web3.namespace" . }}
spec:
  rateLimit: {{ toYaml .Values.ingress.middleware.rateLimit | nindent 4 }}
{{- end -}}
